bigfoot_media:
    resource: "@BigfootMediaBundle/Controller/"
    type:     annotation
    prefix:   /admin

bigfoot_core:
    resource: "@BigfootCoreBundle/Controller/"
    type:     annotation
    prefix:   /admin

bigfoot_user:
    resource: "@BigfootUserBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_seo:
    resource: "@BigfootSeoBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_import:
    resource: "@BigfootImportBundle/Controller/"
    type:     annotation
    prefix:   /