bigfoot_context:
    resource: "@BigfootContextBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_media:
    resource: "@BigfootMediaBundle/Controller/"
    type:     annotation
    prefix:   /admin

bigfoot_core:
    resource: "@BigfootCoreBundle/Controller/"
    type:     annotation
    prefix:   /admin

bigfoot_user:
    resource: "@BigfootUserBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_seo:
    resource: "@BigfootSeoBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_import:
    resource: "@BigfootImportBundle/Controller/"
    type:     annotation
    prefix:   /

bigfoot_navigation:
    resource: "@BigfootNavigationBundle/Controller/"
    type:     annotation
    prefix:   /admin

bigfoot_content:
    resource: "@BigfootContentBundle/Controller/"
    type:     annotation
    prefix:   /admin

_main:
    resource: routing.yml
    prefix:   /
