security:
    firewalls:
        login_firewall:
            pattern: ^/admin/login$
            anonymous:  ~
        back_office:
            pattern: ^/admin/
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/
            logout:
                path:   /admin/logout
                target: /admin/
    providers:
        bigfoot:
            entity:
                class: BigfootUserBundle:BigfootUser
    encoders:
        Bigfoot\Bundle\UserBundle\Entity\BigfootUser:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false
